### ISSUE TITLE
Web Bluetooth: Do not filter services

### ISSUE THREAD

**Issue by ddorwin** [chromium/permission.site#38]
The implementation of the Bluetooth button currently passes `filters: [{services: ['battery_service']}]` to `navigator.bluetooth.requestDevice()`. The result is that only devices that support this service are shown in the resulting UI.

Users of the button would be more likely to see devices and be able to proceed further in the resulting UI if there was no filter applied. For example, https://googlechrome.github.io/samples/web-bluetooth/device-info.html?allDevices=true finds other types of devices.

/cc @beaufortfrancois

**Comment by lgarron** [comment]
Sounds good to me!

**Comment by beaufortfrancois** [comment]
LGTM, I'll file a PR.

**Comment by beaufortfrancois** [comment]
See https://github.com/GoogleChrome/permission.site/pull/39

**Comment by engedy** [comment]
This is fixed now, closing.
