### ISSUE TITLE
Move permission.site registration and hosting

### ISSUE THREAD

**Issue by lgarron** [chromium/permission.site#44]
One plan was to do this once GitHub Pages launched HTTPS support, since we need HTTPS to work. Today's announcement reminds me we still need to do it!

@adrifelt, two questions:
- Is there an Enamel point of contact I should use for the registration migration?
- Other Google projects (that aren't Google products) use GitHub Pages and/or Let's Encrypt; any concerns with using it for permission.site?

**Comment by engedy** [comment]
After some back-and-forth around which domain name to use going forward, we (the Permissions folks), have decided we like permission.site the most, so we would like to take you up on this offer to move the domain registration. In the very near future we are also planning add some extra sub-domains, so maybe now would be as good a time as any to start the process.

**Comment by adrifelt** [comment]
Hi, I want to confirm that engedy is a good owner. Lucas, can you please work with him to transfer it over? We appreciate it. Thank you!

**Comment by lgarron** [comment]
Thanks for the confirmation! I'll unlock the domain and send the EPP via email!

**Comment by engedy** [comment]
Transfer is complete, thank you all for the help and your patience!
