### ISSUE TITLE
http-https toggle is stuck in Android

### ISSUE THREAD

**Issue by hkamila** [chromium/permission.site#51]
The http-https toggle is stuck in Android as seen here:
![15375319696056343](https://user-images.githubusercontent.com/43603801/46071601-b0bdbf00-c180-11e8-92dc-f77068ad26f4.png)

Not sure if a chrome or permission.site issue, but reporting it to keep track of it.

**Comment by lgarron** [comment]
Usually this means Javascript is not running. Could you connect to a
computer and check if the console shoes any issues?

**Comment by hkamila** [comment]
That's right, I missed the fact that I had disabled js. It works just fine.
